package org.example.untitled;// Generated by Selenium IDE

import org.junit.After;
import org.junit.Before;
import org.junit.Test;
import org.openqa.selenium.By;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeDriver;

import java.util.HashMap;
import java.util.Map;

import static org.hamcrest.CoreMatchers.is;
import static org.junit.Assert.assertThat;
public class AdditionTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    System.setProperty("webdriver.chrome.driver","src/main/resources/chromedriver.exe");
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void addition() {
    driver.get("https://calculatrice-squash.web.app/");
    driver.manage().window().setSize(new Dimension(1382, 744));
    driver.findElement(By.id("op1")).sendKeys("1");
    driver.findElement(By.id("op1")).click();
    driver.findElement(By.id("op2")).sendKeys("1");
    driver.findElement(By.id("op2")).click();
    driver.findElement(By.id("plus")).click();
    {
      String value = driver.findElement(By.id("resultOperation")).getAttribute("value");
      assertThat(value, is("2"));
    }
  }
}
